FROM debian:8 AS debian

RUN apt-get update \
 && apt-get install -y git build-essential pkg-config \
    libpcre3-dev libevent-dev \
    libxml2-dev libyaml-dev libssl-dev zlib1g-dev libsqlite3-dev

ARG crystal_targz
COPY ${crystal_targz} /tmp/crystal.tar.gz
ENV PATH=/tmp/crystal/bin:/tmp/crystal/embedded/bin:${PATH}
RUN mkdir -p /tmp/crystal \
 && tar xz -f /tmp/crystal.tar.gz -C /tmp/crystal --strip-component=1

ENV REPOS_DIR /repos
ADD ./setup /setup
RUN /bin/bash -c '/setup/00-install-bats.sh'
RUN /bin/bash -c '/setup/10-clone-repos.sh'
