ARG debian_docker_image
FROM ${debian_docker_image}

RUN apt-get update \
 && apt-get install -y git build-essential tzdata pkg-config software-properties-common curl \
    libpcre3-dev libevent-dev \
    libxml2-dev libyaml-dev libssl-dev zlib1g-dev libsqlite3-dev libgmp-dev \
    libedit-dev libreadline-dev gdb postgresql-client

RUN add-apt-repository "deb http://apt.llvm.org/$(lsb_release -cs)/ llvm-toolchain-$(lsb_release -cs)-4.0 main" \
 && curl -sSL https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add - \
 && apt-get update \
 && apt-get install -y llvm-4.0

ARG crystal_targz
COPY ${crystal_targz} /tmp/crystal.tar.gz
ENV PATH=/tmp/crystal/bin:${PATH}
RUN mkdir -p /tmp/crystal \
 && tar xz -f /tmp/crystal.tar.gz -C /tmp/crystal --strip-component=1
# Only needed to build crystal without installing a separate libgc
ENV LIBRARY_PATH=/tmp/crystal/lib/crystal/lib/

ENV REPOS_DIR /repos
ADD ./scripts /scripts
RUN /bin/bash -c '/scripts/00-install-bats.sh'

ENV SHARDS_CACHE_PATH /shards_cache
