name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      crystal:
        type: string
        default: nightly
      shards:
        type: string
        default: nightly

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.inputs }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  list-tests:
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.list.outputs.files }}
    steps:
      - uses: actions/checkout@v4
      - id: list
        run: |
          files=$(find test -type f -name '*.bats' -print0 | sed -z 's|^test/||' | jq -Rs -c 'split("\u0000")[:-1]')
          echo "files=$files" >> "$GITHUB_OUTPUT"
  test:
    needs: list-tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, windows-2022, macos-15-intel, macos-15]
        file: ${{ fromJson(needs.list-tests.outputs.files) }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v5

      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{ github.event.inputs.crystal || 'nightly' }}
          shards: ${{ github.event.inputs.shards || 'nightly' }}

      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.9.0

      - name: Configure git to not checkout CRLF
        run: git config --global --add core.autocrlf false

      - name: Install OS-specific dependencies
        run: bash ./setup/${{ matrix.os }}.bash

      - name: Test
        run: |
          bats --pretty --timing --filter-tags !format "test/${{ matrix.file }}"
        env:
          WINDOWS_BASE_DIR: "/d/a"
          TERM: dumb

  test_format:
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v5

      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{ github.event.inputs.crystal || 'nightly' }}
          shards: ${{ github.event.inputs.shards || 'nightly' }}

      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.9.0

      - name: Configure git to not checkout CRLF
        run: git config --global --add core.autocrlf false

      - name: Test
        run: |
          bats --pretty --timing test --filter-tags format
        env:
          WINDOWS_BASE_DIR: "/d/a"
          TERM: dumb
